export default defineAppConfig({
  pages: [
    'pages/todo-list/index',
    'pages/target-list/index',
    'pages/plan-list/index',
    'pages/note-list/index',
    'pages/calendar/index',
    'pages/day-view/index',
    'pages/statistics/index',
    'pages/me/index',
    'pages/todo-add/index',
    'pages/target-add/index',
    'pages/target-detail/index',
    'pages/plan-add/index',
    'pages/plan-detail/index',
    'pages/note-add/index',
  ],
  tabBar: {
    color: '#8b8680',
    selectedColor: '#d4726f',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/todo-list/index',
        text: '任务',
        iconPath: 'assets/tab-icons/todo.png',
        selectedIconPath: 'assets/tab-icons/todo-active.png',
      },
      {
        pagePath: 'pages/target-list/index',
        text: '目标',
        iconPath: 'assets/tab-icons/target.png',
        selectedIconPath: 'assets/tab-icons/target-active.png',
      },
      {
        pagePath: 'pages/calendar/index',
        text: '日历',
        iconPath: 'assets/tab-icons/calendar.png',
        selectedIconPath: 'assets/tab-icons/calendar-active.png',
      },
      {
        pagePath: 'pages/statistics/index',
        text: '统计',
        iconPath: 'assets/tab-icons/statistics.png',
        selectedIconPath: 'assets/tab-icons/statistics-active.png',
      },
      {
        pagePath: 'pages/me/index',
        text: '我的',
        iconPath: 'assets/tab-icons/me.png',
        selectedIconPath: 'assets/tab-icons/me-active.png',
      },
    ],
  },
  window: {
    navigationStyle: 'custom',
    backgroundColor: '#f8f8f6',
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTextStyle: 'black',
  },
  lazyCodeLoading: 'requiredComponents',
});
